### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by guotie** [QuilibriumNetwork/ceremonyclient#117]
```
{"level":"error","ts":1710234119.712218,"caller":"ceremony/ceremony_execution_engine.go:583","msg":"error while materializing application from frame","error":"materialize application from frame: get outputs from clock frame: proto: cannot parse invalid wire-format data","errorVerbose":"proto: cannot parse invalid wire-format data\nget outputs from clock frame\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony/application.GetOutputsFromClockFrame\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/application/ceremony_application.go:576\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony/application.MaterializeApplicationFromFrame\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/application/ceremony_application.go:596\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).RunWorker\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:581\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start.func1.1\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:449\nruntime.goexit\n\t/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/src/runtime/asm_arm64.s:1172\nmaterialize application from frame\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony/application.MaterializeApplicationFromFrame\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/application/ceremony_application.go:598\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).RunWorker\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:581\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start.func1.1\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:449\nruntime.goexit\n\t/opt/homebrew/Cellar/go@1.20/1.20.14/libexec/src/runtime/asm_arm64.s:1172","stacktrace":"source.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).RunWorker\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:583\nsource.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start.func1.1\n\t/Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:449"}

panic: materialize application from frame: get outputs from clock frame: proto: cannot parse invalid wire-format data
goroutine 359896 [running]:
source.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).RunWorker(0x14000150b40)
        /Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:587 +0x22bc
source.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start.func1.1()
        /Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:449 +0x20
created by source.quilibrium.com/quilibrium/monorepo/node/execution/intrinsics/ceremony.(*CeremonyExecutionEngine).Start.func1
        /Users/guotie/ceremonyclient/node/execution/intrinsics/ceremony/ceremony_execution_engine.go:448 +0xc4
exit status 2
```

**Comment by guotie** [comment]
v1.4.6

go 1.20.14 

mac M1

**Comment by CassOnMars** [comment]
Thanks for reporting, this has been fixed in the latest main
