### ISSUE TITLE
panic: get clock frame iterator value: invalid data: item not found

### ISSUE THREAD

**Issue by lnzx** [QuilibriumNetwork/ceremonyclient#388]
`{"level":"info","ts":1732523401.2113934,"caller":"data/consensus_frames.go:279","msg":"polling peer for new frames","peer_id":"QmUAWvjhvdFf5h69cTJe4i9gEDLuWocQcKRnikLrUYvLYd","current_frame":60903,"max_frame":62375}
{"level":"info","ts":1732523401.2133293,"logger":"reachability","caller":"p2p/blossomsub.go:334","msg":"node is externally reachable"}
{"level":"info","ts":1732523401.6769822,"caller":"data/consensus_frames.go:351","msg":"received new leading frame","frame_number":60904,"frame_age":187802.01198019}
panic: get clock frame iterator value: invalid data: item not found

goroutine 786 [running]:
source.quilibrium.com/quilibrium/monorepo/node/consensus/time.(*DataTimeReel).runLoop(0xc011ffe900)
/opt/ceremonyclient/node/consensus/time/data_time_reel.go:353 +0x86d
created by source.quilibrium.com/quilibrium/monorepo/node/consensus/time.(*DataTimeReel).Start in goroutine 693
/opt/ceremonyclient/node/consensus/time/data_time_reel.go:178 +0x4d2`

**Comment by BenjixLeGaulois** [comment]
Same issue for me. I already deleted the store folder to regenerate it. Same issue.
